version: '2'

services:

  ## WebApp to cover with BDD or E2E
  keystone:
    image: mahnunchik/keystonejs
    environment:
      - MONGO_PORT_27017_TCP_ADDR=mongo
      - MONGO_PORT_27017_TCP_PORT=27017
      - CLOUDINARY_URL=cloudinary://api_key:api_secret@cloud_name
    ports:
      - 8080:8080
    links:
      - mongo

  ## Related WebApp database
  mongo:
    image: mongo

  ## Client for Selenium real-time inspection
  novnc:
    image: javanile/novnc
    environment:
      - REMOTE_HOST=localhost
      - REMOTE_PORT=5900
    ports:
      - 8081:8081
    links:
      - selenium

  ## Selenium server with Chrome
  selenium:
    image: selenium/standalone-chrome-debug:3.11.0-californium
    environment:
      - VNC_NO_PASSWORD=1
      - SCREEN_WIDTH=640
      - SCREEN_HEIGHT=480
    ports:
      - 4444:4444
      - 5900:5900

  ## Task running environment setting
  task:
    build: ./docker/task
    volumes:
      - ./:/task

  ## Behat command-line utility
  composer:
    entrypoint: composer
    extends:
      service: task

  ## Behat command-line utility
  behat:
    entrypoint: ./vendor/bin/behat
    extends:
      service: task
    links:
      - selenium
